### ISSUE TITLE
Py_InitModule not working in Python3

### ISSUE THREAD

**Issue by dgromer** [mpastell/Rpyplot#2]
The latest commit (https://github.com/mpastell/Rpyplot/commit/09feee40d668d6c0a0a21b741edb9f9027ef7d45) doesn't compile in Python3. I guess that's due to changes in module initialization, see https://docs.python.org/3/howto/cporting.html#module-initialization-and-state

Compile error:

```
pylab.cpp:63:52: error: 'Py_InitModule' was not declared in this scope
```

**Comment by mpastell** [comment]
Thanks for the report. This should be fixed now, note that you'll now need to install libpython (see README) in Windows in order to build the new version.
